/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metrocine;

/**
 *
 * @author Estudiantes
 */
public class InterfazModificar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazModificar
     */
    public InterfazModificar() {
        initComponents();
        textNombre.setEditable(false);
        textNombre.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Elegir = new javax.swing.ButtonGroup();
        elegir2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        botonNo = new javax.swing.JRadioButton();
        textNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));
        setMaximumSize(new java.awt.Dimension(680, 620));
        setMinimumSize(new java.awt.Dimension(680, 620));
        setPreferredSize(new java.awt.Dimension(680, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(680, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(680, 620));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/interfaz/Cinta.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 0, 360, 660);

        botonSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/interfaz/Cinta.png"))); // NOI18N
        jPanel1.add(botonSi);
        botonSi.setBounds(-210, 0, 360, 660);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Indique tipo de sala");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 370, 240, 20);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 255));
        Elegir.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Si");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(130, 70, 39, 25);

        botonNo.setBackground(new java.awt.Color(0, 0, 255));
        Elegir.add(botonNo);
        botonNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonNo.setForeground(new java.awt.Color(255, 255, 255));
        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });
        jPanel1.add(botonNo);
        botonNo.setBounds(250, 70, 93, 23);

        textNombre.setText("Nombre Sucursal");
        jPanel1.add(textNombre);
        textNombre.setBounds(130, 110, 210, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿Desea Agregar una sucursal?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 20, 240, 20);

        jRadioButton5.setBackground(new java.awt.Color(0, 0, 255));
        elegir2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("No");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(250, 230, 93, 23);

        jRadioButton7.setBackground(new java.awt.Color(0, 0, 255));
        elegir2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Si");
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(130, 230, 39, 25);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(120, 320, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿Desea agregar una sala?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 180, 240, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Indique la sucursal");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 280, 240, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2D", "3D", "4DX" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(120, 440, 160, 20);

        jButton1.setText("Enviar");
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 520, 63, 23);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver);
        botonVolver.setBounds(440, 10, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        Inicio inicio=new Inicio();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        textNombre.setEditable(true);
        textNombre.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // TODO add your handling code here:
        textNombre.setEditable(false);
        textNombre.setEnabled(false);
    }//GEN-LAST:event_botonNoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Elegir;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JLabel botonSi;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup elegir2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
