/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metrocine;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class InterfazModificar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazModificar
     */
        private MetroCine cine;
    public InterfazModificar(MetroCine cine) {
        initComponents();
        textNombre.setEditable(false);
        textNombre.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.cine=cine;
        botonSucursal.setEnabled(false);
        botonSala.setEnabled(false);
        
    }
    private void InsertarUbicacion(Sucursal aux){
         if(aux != null){
            
            this.InsertarUbicacion(aux.gethIzquierdo());
            listaSucursal.addItem(aux.getUbicacion());            
            this.InsertarUbicacion(aux.gethDerecho()); 
            
        }
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Elegir = new javax.swing.ButtonGroup();
        elegir2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cinta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonSi = new javax.swing.JRadioButton();
        botonNo = new javax.swing.JRadioButton();
        textNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonNo2 = new javax.swing.JRadioButton();
        botonSi2 = new javax.swing.JRadioButton();
        listaSucursal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listaTipoSala = new javax.swing.JComboBox();
        botonVolver = new javax.swing.JButton();
        botonSucursal = new javax.swing.JButton();
        botonSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));
        setMaximumSize(new java.awt.Dimension(680, 620));
        setMinimumSize(new java.awt.Dimension(680, 620));
        setPreferredSize(new java.awt.Dimension(680, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(680, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(680, 620));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/interfaz/Cinta.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 0, 360, 660);

        Cinta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/interfaz/Cinta.png"))); // NOI18N
        jPanel1.add(Cinta);
        Cinta.setBounds(-210, 0, 360, 660);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Indique tipo de sala");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 370, 240, 20);

        botonSi.setBackground(new java.awt.Color(0, 0, 255));
        Elegir.add(botonSi);
        botonSi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonSi.setForeground(new java.awt.Color(255, 255, 255));
        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });
        jPanel1.add(botonSi);
        botonSi.setBounds(130, 70, 39, 25);

        botonNo.setBackground(new java.awt.Color(0, 0, 255));
        Elegir.add(botonNo);
        botonNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonNo.setForeground(new java.awt.Color(255, 255, 255));
        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });
        jPanel1.add(botonNo);
        botonNo.setBounds(250, 70, 93, 23);
        jPanel1.add(textNombre);
        textNombre.setBounds(130, 110, 210, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿Desea Agregar una sucursal?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 20, 240, 20);

        botonNo2.setBackground(new java.awt.Color(0, 0, 255));
        elegir2.add(botonNo2);
        botonNo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonNo2.setForeground(new java.awt.Color(255, 255, 255));
        botonNo2.setText("No");
        botonNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNo2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonNo2);
        botonNo2.setBounds(250, 230, 93, 23);

        botonSi2.setBackground(new java.awt.Color(0, 0, 255));
        elegir2.add(botonSi2);
        botonSi2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonSi2.setForeground(new java.awt.Color(255, 255, 255));
        botonSi2.setText("Si");
        botonSi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSi2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSi2);
        botonSi2.setBounds(130, 230, 39, 25);

        listaSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(listaSucursal);
        listaSucursal.setBounds(120, 320, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿Desea agregar una sala?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 180, 240, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Indique la sucursal");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 280, 240, 20);

        listaTipoSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2D", "3D", "4DX" }));
        jPanel1.add(listaTipoSala);
        listaTipoSala.setBounds(120, 440, 160, 20);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver);
        botonVolver.setBounds(440, 10, 90, 23);

        botonSucursal.setText("Agregar Sucursal");
        botonSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(botonSucursal);
        botonSucursal.setBounds(380, 110, 150, 23);

        botonSala.setText("Agregar Sala");
        botonSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalaActionPerformed(evt);
            }
        });
        jPanel1.add(botonSala);
        botonSala.setBounds(390, 440, 160, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaSucursalActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        Inicio inicio=new Inicio(cine);
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
        textNombre.setEditable(true);
        textNombre.setEnabled(true);
        botonSucursal.setEnabled(true);
  
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // TODO add your handling code here:
        textNombre.setEditable(false);
        textNombre.setEnabled(false);
        botonSucursal.setEnabled(false);
    }//GEN-LAST:event_botonNoActionPerformed

    private void botonSi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSi2ActionPerformed
     
       this.InsertarUbicacion(this.cine.getSucursales().getRaiz());
       botonSala.setEnabled(true);
        
    }//GEN-LAST:event_botonSi2ActionPerformed

    private void botonNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNo2ActionPerformed
        listaSucursal.setEnabled(false);
        listaTipoSala.setEnabled(false);
        botonSala.setEnabled(false);
    }//GEN-LAST:event_botonNo2ActionPerformed

    private void botonSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSucursalActionPerformed
        // TODO add your handling code here:
        botonSala.setEnabled(true);
        if(!textNombre.getText().equals("")){
            
            cine.getSucursales().insertarSucursal(cine.getSucursales().getRaiz(), new Sucursal(textNombre.getText(),0,0,0));
        }
        else{
            //que aparezca ventana emergente
            
     JOptionPane.showMessageDialog(null, "No ha escrito el nombre de la sucursal", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
      
    }//GEN-LAST:event_botonSucursalActionPerformed

    private void botonSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalaActionPerformed
        // TODO add your handling code here:
      Sucursal aux=cine.getSucursales().BuscarPorUbicacion(cine.getSucursales().getRaiz(), (String) listaSucursal.getItemAt(listaSucursal.getSelectedIndex()));
      if("2D".equals((String)listaTipoSala.getItemAt(listaTipoSala.getSelectedIndex()))){
          aux.AgregarSala2D();
      }
      else if("3D".equals((String)listaTipoSala.getItemAt(listaTipoSala.getSelectedIndex()))){
          aux.AgregarSala3D();
      }
      else{
          aux.AgregarSala4DX();
      }
      
        
    }//GEN-LAST:event_botonSalaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cinta;
    private javax.swing.ButtonGroup Elegir;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JRadioButton botonNo2;
    private javax.swing.JButton botonSala;
    private javax.swing.JRadioButton botonSi;
    private javax.swing.JRadioButton botonSi2;
    private javax.swing.JButton botonSucursal;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup elegir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox listaSucursal;
    private javax.swing.JComboBox listaTipoSala;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
